print(False and False or True and False)
print(False and False)
print(True and False)
print(False and True)
print(True and True)

print(True or True)
print(False or True)
print(True or False)
print(False or False)